version: '2'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - '.:/ner-api'
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "ner_api.app:create_app()" 
    links:
      - mongo 
    depends_on:
      - mongo 

  mongo:
    image: mongo:3.6
    ports:            # DELETE PORTS FOR PRODUCTION
      - "27017:27017" 
    